### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by CrafteeD** [pjc0247/jenkins-client.net#2]
If we're interested in forking and using some of your code, is there a particular open source license you plan to release this under?

**Comment by pjc0247** [comment]
@CrafteeD Hi.
It's a public domain project. You can edit or release your own version of it freely.

**Comment by CrafteeD** [comment]
@pjc0247 Thanks for the response!

Do you think you could help out by adding a license file that matches that intent to the repository?

The MIT license should be a good fit: 
[https://opensource.org/licenses/MIT](https://opensource.org/licenses/MIT)

It would really help out - thanks!

**Comment by pjc0247** [comment]
@CrafteeD Sure! 

https://github.com/pjc0247/jenkins-client.net/commit/81d36c15ac718a4abc7ffea81724bbef99f7ae9e

**Comment by CrafteeD** [comment]
Thanks @pjc0247, that really helps!
